apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: aspnetapp
spec:
  selector:
    matchLabels:
      app: aspnetapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: dmnt3d/dotnet-aspnetapp@sha256:c6ccbb0f55c2a53fc526489e582a0d35b6e20f27cb3295440af49a0c1382a9d4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
      
      restartPolicy: Always