apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: aspnetapp
spec:
  selector:
    matchLabels:
      app: aspnetapp
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: dmnt3d/dotnet-aspnetapp@sha256:443cc1487fa5ca726264cda2269cc790cdd147eb6f8ea0a1f087cd3b0e9d6da1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
      
      restartPolicy: Always