apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: aspnetapp
spec:
  selector:
    matchLabels:
      app: aspnetapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: dmnt3d/dotnet-aspnetapp:b15.20220505.051201
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
      
      restartPolicy: Always